// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ArtDirections.tsx": () => import("../components/mockups/ArtDirections.tsx"),
  "./components/mockups/InEngineDirections.tsx": () => import("../components/mockups/InEngineDirections.tsx"),
  "./components/mockups/MapStyleLab.tsx": () => import("../components/mockups/MapStyleLab.tsx"),
  "./components/mockups/OverworldExpansion.tsx": () => import("../components/mockups/OverworldExpansion.tsx"),
  "./components/mockups/StyleCompare.tsx": () => import("../components/mockups/StyleCompare.tsx")
};
